# Generated by Django 5.1.4 on 2026-09-09 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='비워두면 사이트에 공개되지 않습니다. 미래 시각으로 두면 그때부터 공개됩니다.', null=True),
        ),
    ]
