# Generated by Django 5.1.4 on 2026-09-16 08:52

import apps.boards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=apps.boards.models.attachment_upload_to, verbose_name='파일')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='종류')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='크기(바이트)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boards.post')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
                'ordering': ('id',),
            },
        ),
    ]
