# Generated by Django 5.1.4 on 2026-09-13 15:07

import apps.studies.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_alter_study_leader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('due_at', models.DateTimeField(verbose_name='제출 기한')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='studies.study')),
            ],
            options={
                'ordering': ('due_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=apps.studies.models.submission_upload_to, verbose_name='제출 파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('size', models.PositiveBigIntegerField(verbose_name='크기(바이트)')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='제출 시각')),
                ('review_status', models.CharField(choices=[('pending', '미확인'), ('checked', '확인')], default='pending', max_length=10, verbose_name='확인 여부')),
                ('feedback', models.TextField(blank=True, verbose_name='피드백')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 시각')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='studies.assignment')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='studies.participation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='회차')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='주제')),
                ('held_on', models.DateField(verbose_name='진행일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studies.study')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '출석'), ('late', '지각'), ('absent', '결석'), ('excused', '공결')], max_length=10, verbose_name='출석 상태')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='studies.participation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='studies.studysession')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmentSubmit',
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'participation'), name='unique_submission_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('study', 'number'), name='unique_session_number_per_study'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('session', 'participation'), name='unique_attendance_per_session'),
        ),
    ]
