# Generated by Django 5.1.4 on 2026-09-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_session_attendance_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='completion_requirements',
            field=models.TextField(blank=True, help_text='예: 출석 80% 이상, 과제 제출', verbose_name='수료 요건'),
        ),
        migrations.AddField(
            model_name='study',
            name='method',
            field=models.TextField(blank=True, help_text='예: 대면 · 매주 발표와 실습', verbose_name='진행 방식'),
        ),
        migrations.AddField(
            model_name='study',
            name='schedule',
            field=models.TextField(blank=True, help_text='예: 매주 화요일 19:00, 3월 둘째 주 ~ 6월 첫째 주', verbose_name='일정'),
        ),
    ]
