# Generated by Django 5.1.4 on 2026-09-28 14:14

import apps.studies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_info_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('notice', '공지'), ('material', '자료')], default='notice', max_length=10, verbose_name='분류')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='studies.study')),
            ],
            options={
                'verbose_name': '스터디 게시글',
                'verbose_name_plural': '스터디 게시글',
                'ordering': ('-is_pinned', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StudyPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=apps.studies.models.study_post_upload_to, verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='종류')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='크기(바이트)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='studies.studypost')),
            ],
            options={
                'verbose_name': '스터디 게시글 첨부',
                'verbose_name_plural': '스터디 게시글 첨부',
                'ordering': ('id',),
            },
        ),
    ]
