# Generated by Django 5.1.4 on 2026-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('dormant', '휴회원'), ('member', '정회원'), ('leader', '스터디장'), ('admin', '운영진')], default='member', max_length=10, verbose_name='권한'),
        ),
    ]
